openapi: 3.0.2

info:
  title: "Pets"
  version: 1.0.0
  description: "Endpoints for pets"

servers:
  - url: http://petstore.your.server.url

paths:
  /v1/pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: An array of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../shared/pet.yaml#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../shared/error.yaml#/components/schemas/Error"