openapi: 3.0.2

info:
  title: "Pet Store"
  version: 1.0.0
  description: "Endpoints for the pet store"

servers:
  - url: http://petstore.your.server.url

paths:
  /v1/store-info:
    get:
      summary: Get information about the pet store
      operationId: storeInfo
      tags:
        - store
      responses:
        '200':
          description: Info about the pet store
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StoreInfo"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../shared/error.yaml#/components/schemas/Error"

components:
  schemas:
    StoreInfo:
      type: object
      required:
        - phoneNumber
        - address
        - recentPets
      properties:
        phoneNumber:
          type: string
        address:
          type: string
        recentPets:
          type: array
          items:
            $ref: "../shared/pet.yaml#/components/schemas/Pet"
